name: compile-and-test-C-program

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
 

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up compiler
        run: sudo apt-get install -y 

      - name: Compile C program
        run: ${{ matrix.compiler }} -o hello_world.exe hello.c

      - name: Run tests
        run: |
          if ./hello_world.exe; then
            echo "Test Passed"
          else
            echo "Test Failed"
            exit 1
          fi
