name: Compile and Test C Program

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang] 

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up compiler
        run: sudo apt-get install -y ${{ matrix.compiler }}

      - name: Compile C program
        run: ${{ matrix.compiler }} -o hello_world.exe hello.c

      - name: Run tests
        run: |
          if ./hello_world.exe; then
            echo "Test Passed"
          else
            echo "Test Failed"
            exit 1
          fi
        
      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
            name: ${{ matrix.compiler }}_hello_world
            path: hello_world.exe
            retention-days: 1