name: vulnerable-secret

on: 
  workflow_dispatch:
    inputs:
      code:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: enter username and password
        run: |
          echo ${{ secrets.password }}
          echo ${{ inputs.code }}
      